# render.yaml
services:
  - name: postiz-postgres
    type: database
    plan: starter
    databaseName: postiz-db-local
    user: postiz-local
    password: postiz-local-pwd

  - name: postiz-redis
    type: redis
    plan: starter

  - name: postiz-pg-admin
    type: web
    env: docker
    docker:
      image: dpage/pgadmin4:latest
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
    plan: starter
    healthCheckPath: /
    ports:
      - 80

  - name: postiz-redisinsight
    type: web
    env: docker
    docker:
      image: redis/redisinsight:latest
    plan: starter
    healthCheckPath: /
    ports:
      - 5540
