services:
  - type: web
    name: postiz-app-devcontainer
    env: docker
    dockerfilePath: ./Dockerfile
    dockerfileTarget: devcontainer
    buildCommand: npm ci --no-fund && npx nx run-many --target=build --projects=frontend,backend,workers,cron
    startCommand: /app/entrypoint.sh
    envVars:
      - key: NODE_VERSION
        value: "20.17"
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    mounts:
      - type: volume
        path: /config
      - type: volume
        path: /uploads
    ports:
      - 3000
      - 4200
      - 5000
    labels:
      - key: org.opencontainers.image.title
        value: "Postiz App (DevContainer)"
      - key: org.opencontainers.image.source
        value: "https://github.com/gitroomhq/postiz-app"

  - type: web
    name: postiz-app-dist
    env: docker
    dockerfilePath: ./Dockerfile
    dockerfileTarget: dist
    startCommand: /app/entrypoint.sh
    envVars:
      - key: NODE_VERSION
        value: "20.17"
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    mounts:
      - type: volume
        path: /config
      - type: volume
        path: /uploads
    ports:
      - 3000
      - 4200
      - 5000
    labels:
      - key: org.opencontainers.image.title
        value: "Postiz App (Production)"
      - key: org.opencontainers.image.source
        value: "https://github.com/gitroomhq/postiz-app"

volumes:
  - name: config
    type: persistent
    storageClass: standard
    path: /config

  - name: uploads
    type: persistent
    storageClass: standard
    path: /uploads
