services:
  # PostgreSQL Database Service
  - type: pserv
    name: postiz-postgres
    env: docker
    docker:
      image: postgres:17-alpine
    envVars:
      - key: POSTGRES_PASSWORD
        value: postiz-local-pwd
      - key: POSTGRES_USER
        value: postiz-local
      - key: POSTGRES_DB
        value: postiz-db-local
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  # Redis Service
  - type: pserv
    name: postiz-redis
    env: docker
    docker:
      image: redis:7-alpine
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 5

  # PgAdmin Web Interface
  - type: web
    name: postiz-pg-admin
    env: docker
    docker:
      image: dpage/pgadmin4:latest
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
    healthCheckPath: /
    internalPort: 80

  # RedisInsight Web Interface
  - type: web
    name: postiz-redisinsight
    env: docker
    docker:
      image: redis/redisinsight:latest
    envVars:
      - key: REDIS_HOST
        fromService:
          name: postiz-redis
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: postiz-redis
          type: pserv
          property: port
    mounts:
      - type: volume
        name: redisinsight-data
        mountPath: /data
    healthCheckPath: /
    internalPort: 5540

volumes:
  - name: postgres-data
  - name: redis-data
  - name: redisinsight-data
